/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ClassObjet.Employee;
import exceptions.CryptoException;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.Crypto;

/**
 *
 * @author Guillaume
 */
public class JFMain extends javax.swing.JFrame {

    Employee loggedEmp;

    JPCustomerTest jpc;

    public JFMain() {
        initComponents();

        loggedEmp = new Employee();
        loggedEmp.setEmpFirstName("Camille");
        loggedEmp.setEmpLastName("Vasseur");
        loggedEmp.setEmpLogin("1");
        loggedEmp.setEmpSalt("k71nhc5h933kblk4oaouihdhh6");
        loggedEmp.setEmpPassword("32D601355049CDBC0E69DA955DACBC271D1A19999043ED1FAAD09F211E433E0917195DF7EC8A09D1B6C223875036CC11A332178B0E97FDEE28AC982938DE96B3");

        /////// BYPASS CREDENTIALS
        //firstRun();
        jPanelCredentials.setVisible(false);
        initWorkSpace();
       /////// BYPASS CREDENTIALS

    }

    private void firstRun() {
        jPanelCredentials.setVisible(true);
        jPanelGeneralInfos.setVisible(false);
        jTabbedPaneGeneral.setVisible(false);
        jLabelWrongCredentials.setVisible(false);
    }

    private void disconnectFromWorkSpace() {
        jTabbedPaneGeneral.setVisible(false);
        jPanelCredentials.setVisible(true);
        jlLoggedEmpFirstName.setText("");
        jlLoggedEmpLastName.setText("");
        jPanelGeneralInfos.setVisible(false);

    }

    private void requestEmployeeCredentials() throws NoSuchAlgorithmException {

        String inputUsername = jtfUsername.getText();
        char[] inputPassChar = jPasswordField.getPassword();
        String inputPassStr = new String(inputPassChar);
        String inputPass = null;

        /**
         * *********************************************************
         *
         * HERE : SQL CODE TO QUERY DATABASE ABOUT USERNAME
         *
         * SELECT * FROM Employee WHERE empLogin = 'inputUsername'
         *
         * If exists : pass arguments (salt & hashpsswd) to Crypto utility
         *
         ***********************************************************
         */
        try {
            inputPass = Crypto.hashPassword(loggedEmp.getEmpSalt(), inputPassStr);
        } catch (CryptoException ex) {
            Logger.getLogger(JFMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!inputUsername.equalsIgnoreCase(loggedEmp.getEmpLogin()) || !inputPass.equalsIgnoreCase(loggedEmp.getEmpPassword())) {
            jLabelWrongCredentials.setVisible(true);
        } else {
            initWorkSpace();
        }
    }

    private void initWorkSpace() {
        clearCredentials();
        initJpanelGeneralInfos();
        initjTabbedGeneral();
    }

    private void clearCredentials() {
        jPanelCredentials.setVisible(false);
        jLabelWrongCredentials.setVisible(false);
        jtfUsername.setText("");
        jPasswordField.setText("");
    }

    private void initJpanelGeneralInfos() {
        jlLoggedEmpFirstName.setText(loggedEmp.getEmpFirstName());
        jlLoggedEmpLastName.setText(loggedEmp.getEmpLastName());
        jPanelGeneralInfos.setVisible(true);

    }

    private void initjTabbedGeneral() {
        jTabbedPaneGeneral.setVisible(true);
        jTabbedPaneGeneral.setSelectedComponent(jpStatistics);
        jpc = new JPCustomerTest();
        Dimension dim = new Dimension(1003, 621);
        jpc.setSize(dim);
        jpc.setVisible(true);
        jpCustomers.add(jpc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabelLogoLibrary = new javax.swing.JLabel();
        jPanelGeneralInfos = new javax.swing.JPanel();
        jlLoggedEmpFirstName = new javax.swing.JLabel();
        jlLoggedEmpLastName = new javax.swing.JLabel();
        jlGenInfoDisconnect = new javax.swing.JLabel();
        JLPendingReviews = new javax.swing.JLabel();
        jTabbedPaneGeneral = new javax.swing.JTabbedPane();
        jpCustomers = new javax.swing.JPanel();
        jpReviews = new javax.swing.JPanel();
        jpOffers = new javax.swing.JPanel();
        jpStatistics = new javax.swing.JPanel();
        jpEmployees = new javax.swing.JPanel();
        jpOrders = new javax.swing.JPanel();
        jPanelCredentials = new javax.swing.JPanel();
        jLabelLibraryName = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelWrongCredentials = new javax.swing.JLabel();
        jButtonConnexion = new javax.swing.JButton();
        jLabelTeamIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyLibrary Management Software");
        setResizable(false);

        jLabelLogoLibrary.setIcon(new javax.swing.ImageIcon("C:\\Users\\cdi308\\Documents\\NetBeansProjects\\Librairie\\MyLibrary\\src\\pictures\\Library-logo.png")); // NOI18N
        jLabelLogoLibrary.setText("Libray Logo");
        jDesktopPane2.add(jLabelLogoLibrary);
        jLabelLogoLibrary.setBounds(10, 11, 346, 87);

        jlLoggedEmpFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlLoggedEmpFirstName.setText("Employee First Name");

        jlLoggedEmpLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlLoggedEmpLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlLoggedEmpLastName.setText("Employee Last Name");

        jlGenInfoDisconnect.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jlGenInfoDisconnect.setForeground(new java.awt.Color(255, 0, 0));
        jlGenInfoDisconnect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlGenInfoDisconnect.setText("Disconnect");
        jlGenInfoDisconnect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenInfoDisconnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlGenInfoDisconnectMouseReleased(evt);
            }
        });

        JLPendingReviews.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPendingReviews.setForeground(new java.awt.Color(255, 102, 0));
        JLPendingReviews.setText("7 pending reviews");
        JLPendingReviews.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLPendingReviews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLPendingReviewsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelGeneralInfosLayout = new javax.swing.GroupLayout(jPanelGeneralInfos);
        jPanelGeneralInfos.setLayout(jPanelGeneralInfosLayout);
        jPanelGeneralInfosLayout.setHorizontalGroup(
            jPanelGeneralInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeneralInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeneralInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlGenInfoDisconnect)
                    .addComponent(jlLoggedEmpLastName)
                    .addGroup(jPanelGeneralInfosLayout.createSequentialGroup()
                        .addComponent(JLPendingReviews)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jlLoggedEmpFirstName)))
                .addGap(20, 20, 20))
        );
        jPanelGeneralInfosLayout.setVerticalGroup(
            jPanelGeneralInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralInfosLayout.createSequentialGroup()
                .addGroup(jPanelGeneralInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeneralInfosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlLoggedEmpFirstName))
                    .addGroup(jPanelGeneralInfosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLPendingReviews)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlLoggedEmpLastName)
                .addGap(12, 12, 12)
                .addComponent(jlGenInfoDisconnect)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jDesktopPane2.add(jPanelGeneralInfos);
        jPanelGeneralInfos.setBounds(701, 11, 297, 87);

        javax.swing.GroupLayout jpCustomersLayout = new javax.swing.GroupLayout(jpCustomers);
        jpCustomers.setLayout(jpCustomersLayout);
        jpCustomersLayout.setHorizontalGroup(
            jpCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jpCustomersLayout.setVerticalGroup(
            jpCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        jTabbedPaneGeneral.addTab("Customers", jpCustomers);

        javax.swing.GroupLayout jpReviewsLayout = new javax.swing.GroupLayout(jpReviews);
        jpReviews.setLayout(jpReviewsLayout);
        jpReviewsLayout.setHorizontalGroup(
            jpReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jpReviewsLayout.setVerticalGroup(
            jpReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        jTabbedPaneGeneral.addTab("Reviews", jpReviews);

        javax.swing.GroupLayout jpOffersLayout = new javax.swing.GroupLayout(jpOffers);
        jpOffers.setLayout(jpOffersLayout);
        jpOffersLayout.setHorizontalGroup(
            jpOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jpOffersLayout.setVerticalGroup(
            jpOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        jTabbedPaneGeneral.addTab("Offers", jpOffers);

        javax.swing.GroupLayout jpStatisticsLayout = new javax.swing.GroupLayout(jpStatistics);
        jpStatistics.setLayout(jpStatisticsLayout);
        jpStatisticsLayout.setHorizontalGroup(
            jpStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jpStatisticsLayout.setVerticalGroup(
            jpStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        jTabbedPaneGeneral.addTab("Statistics", jpStatistics);

        javax.swing.GroupLayout jpEmployeesLayout = new javax.swing.GroupLayout(jpEmployees);
        jpEmployees.setLayout(jpEmployeesLayout);
        jpEmployeesLayout.setHorizontalGroup(
            jpEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jpEmployeesLayout.setVerticalGroup(
            jpEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        jTabbedPaneGeneral.addTab("Employees", jpEmployees);

        javax.swing.GroupLayout jpOrdersLayout = new javax.swing.GroupLayout(jpOrders);
        jpOrders.setLayout(jpOrdersLayout);
        jpOrdersLayout.setHorizontalGroup(
            jpOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jpOrdersLayout.setVerticalGroup(
            jpOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        jTabbedPaneGeneral.addTab("Orders management", jpOrders);

        jDesktopPane2.add(jTabbedPaneGeneral);
        jTabbedPaneGeneral.setBounds(0, 116, 1008, 613);

        jPanelCredentials.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLibraryName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelLibraryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLibraryName.setText("MyLibrary Management Software");

        jLabelUsername.setText("Username");

        jtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameActionPerformed(evt);
            }
        });

        jLabelPassword.setText("Password");

        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
        });
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyReleased(evt);
            }
        });

        jLabelWrongCredentials.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelWrongCredentials.setForeground(new java.awt.Color(255, 0, 0));
        jLabelWrongCredentials.setText("Wrong username or password");

        jButtonConnexion.setText("Connexion");
        jButtonConnexion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnexionActionPerformed(evt);
            }
        });

        jLabelTeamIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\cdi308\\Documents\\NetBeansProjects\\Librairie\\MyLibrary\\src\\pictures\\logo_poussin.png")); // NOI18N

        javax.swing.GroupLayout jPanelCredentialsLayout = new javax.swing.GroupLayout(jPanelCredentials);
        jPanelCredentials.setLayout(jPanelCredentialsLayout);
        jPanelCredentialsLayout.setHorizontalGroup(
            jPanelCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCredentialsLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanelCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLibraryName)
                    .addComponent(jButtonConnexion)
                    .addComponent(jLabelWrongCredentials))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTeamIcon)
                .addContainerGap())
        );
        jPanelCredentialsLayout.setVerticalGroup(
            jPanelCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCredentialsLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelLibraryName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCredentialsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTeamIcon)
                        .addContainerGap())
                    .addGroup(jPanelCredentialsLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelWrongCredentials)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButtonConnexion)
                        .addGap(24, 24, 24))))
        );

        jDesktopPane2.add(jPanelCredentials);
        jPanelCredentials.setBounds(263, 216, 481, 297);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1024, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JLPendingReviewsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLPendingReviewsMouseReleased
        //jTabbedPane6.setSelectedIndex(2);
        jTabbedPaneGeneral.setSelectedComponent(jpReviews);
    }//GEN-LAST:event_JLPendingReviewsMouseReleased

    private void jButtonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnexionActionPerformed
        try {
            this.requestEmployeeCredentials();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(JFMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConnexionActionPerformed

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        jPasswordField.setText("");
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsernameActionPerformed

    private void jlGenInfoDisconnectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenInfoDisconnectMouseReleased
        disconnectFromWorkSpace();
    }//GEN-LAST:event_jlGenInfoDisconnectMouseReleased

    private void jPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                this.requestEmployeeCredentials();
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(JFMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jPasswordFieldKeyReleased

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLPendingReviews;
    private javax.swing.JButton jButtonConnexion;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabelLibraryName;
    private javax.swing.JLabel jLabelLogoLibrary;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelTeamIcon;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelWrongCredentials;
    private javax.swing.JPanel jPanelCredentials;
    private javax.swing.JPanel jPanelGeneralInfos;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTabbedPane jTabbedPaneGeneral;
    private javax.swing.JLabel jlGenInfoDisconnect;
    private javax.swing.JLabel jlLoggedEmpFirstName;
    private javax.swing.JLabel jlLoggedEmpLastName;
    private javax.swing.JPanel jpCustomers;
    private javax.swing.JPanel jpEmployees;
    private javax.swing.JPanel jpOffers;
    private javax.swing.JPanel jpOrders;
    private javax.swing.JPanel jpReviews;
    private javax.swing.JPanel jpStatistics;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
